### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by zek** [ICObench/data-api#9]
I cant use api. I tried python and php.
Everytime I get urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by resida** [comment]
Hi Talha, 
were you able to resolve this in any way. I'm getting the same response and sometimes I get html as opposed to JSON being returned.

**Comment by zek** [comment]
I guess API is not working anymore or they blocked my account.

**Comment by resida** [comment]
Ok makes sense. I'm still getting the same error, will experiment with new account. Cheers.
